apiVersion: v1
kind: Pod
metadata:
  name: hello123
#  namespace: test
spec:
  containers:
    - name: nginx
      image: nginxdemos/hello:plain-text
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
