apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-foo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      domain: foo
  template:
    metadata:
      labels:
        app: nginx
        domain: foo
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: NAME
              valueFrom:
                configMapKeyRef:
                    name: nginx-cm
                    key: foo-name
          command:
            - sh
            - -c
            - |
              H=$(echo $HOSTNAME | rev |  cut -d "-" -f1 | rev)
              sed -e "s/{{name}}/$NAME/g" -e "s/{{hostname}}/$HOSTNAME/g" /usr/share/nginx/html/index.html > /usr/share/nginx/html/$NAME_$H.html
              sed -i "s/index.html/$NAME_$H.html/g" /etc/nginx/conf.d/default.conf
              nginx -g 'daemon off;';
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: workdir
              mountPath: /usr/share/nginx/html
      volumes:
        - name: workdir
          hostPath:
            path: /home/docker/workdir
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-bar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      domain: bar
  template:
    metadata:
      labels:
        app: nginx
        domain: bar
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: NAME
              valueFrom:
                configMapKeyRef:
                  name: nginx-cm
                  key: bar-name
          command:
            - sh
            - -c
            - |
              H=$(echo $HOSTNAME | rev |  cut -d "-" -f1 | rev)
              sed -e "s/{{name}}/$NAME/g" -e "s/{{hostname}}/$HOSTNAME/g" /usr/share/nginx/html/index.html > /usr/share/nginx/html/$NAME_$H.html
              sed -i "s/index.html/$NAME_$H.html/g" /etc/nginx/conf.d/default.conf
              nginx -g 'daemon off;';
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: workdir
              mountPath: /usr/share/nginx/html
      volumes:
        - name: workdir
          hostPath:
            path: /home/docker/workdir