apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-foo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: NAME
              value: foo
          command:
            - sh
            - -c
            - |
              sed -e "s/{{name}}/$NAME/g" -e "s/{{hostname}}/$HOSTNAME/g" /usr/share/nginx/html/index.html > /usr/share/nginx/html/$NAME.html
              sed -i "s/index.html/$NAME.html/g" /etc/nginx/conf.d/default.conf
              nginx -g 'daemon off;';
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: workdir
              mountPath: /usr/share/nginx/html
      volumes:
        - name: workdir
          hostPath:
            path: /home/docker/workdir
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-bar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: NAME
              value: bar
          command:
            - sh
            - -c
            - |
              sed -e "s/{{name}}/$NAME/g" -e "s/{{hostname}}/$HOSTNAME/g" /usr/share/nginx/html/index.html > /usr/share/nginx/html/$NAME.html
              sed -i "s/index.html/$NAME.html/g" /etc/nginx/conf.d/default.conf
              nginx -g 'daemon off;';
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: workdir
              mountPath: /usr/share/nginx/html
      volumes:
        - name: workdir
          hostPath:
            path: /home/docker/workdir