apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      name: hello
      labels:
        app: hello
    spec:
      containers:
      - name: go
        image: ezuoo/go:v3
        ports:
        - name: http
          containerPort: 8090
          protocol: TCP
