---
- name: Test on Master
  hosts: ubuntu
  become: true
  tasks:
    - name: 'Install Nginx'
      apt:
        name: nginx
        state: present
        update_cache: true

    - name: 'Ensure nginx service started'
      service:
        name: nginx
        state: started

- name: Test on Master
  hosts: worker
  become: true
  tasks:
    - name: 'Enable Nginx repository provided by Amazon'
      command: 'amazon-linux-extras enable nginx1'

    - name: 'Install Nginx'
      yum:
        name: nginx
        state: present

    - name: 'Ensure nginx service started'
      service:
        name: nginx
        state: started
