---
- name: Clean-up apt repo
  hosts: all
  become: true
  docker_package_dependency:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc
  tasks:
    - name: Apt docker repo
      script: ./repo/docker-unset.sh