apiVersion: apps/v1
kind: Deployment
metadata:
  name: jawn
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  revisionHistoryLimit: 5
  replicas: 5
  selector:
    matchLabels:
      app: jawn
  template:
    metadata:
      name: jawn
      labels:
        app: jawn
    spec:
      containers:
      - name: go
        image: ezuoo/go:v3
        ports:
        - name: http
          containerPort: 8090
          protocol: TCP
