apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      name: config
      labels:
        app: config
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - name: http
          containerPort: 3306
          protocol: TCP
        envFrom:
        - configMapRef:
            name: config
#        - name: MYSQL_ROOT_PASSWORD
#          value: asdf1234

